[package]
name = "pdf_maker"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde = { version = "1.0.217", features = ["derive"] }
rust_xlsxwriter = "0.81.0"
actix-ws = "0.3.0"
futures-util = "0.3.31"
mysql = "25.0.1"
dotenv = "0.15.0"
dotenv_codegen = "0.15.0"
